### ISSUE TITLE
ERROR: creating buildpack from .: buildpack.version is required

### ISSUE THREAD

**Issue by Souljacker2** [dmikusa/paketo-arm64#10]
Hi,
When running [build.sh script](https://github.com/dmikusa/paketo-arm64/blob/main/scripts/build.sh) (last step on [Package your Buildpacks](https://github.com/dmikusa/paketo-arm64#package-your-buildpacks)) I'm getting:
`ERROR: creating buildpack from .: buildpack.version is required`

Here are my steps:
1. `./scripts/clone.sh paketo-buildpacks/java 9.3.0`
2. `find ./buildpacks  -name "buildpack.toml" | xargs -n 1 ./scripts/mod-bptoml.sh`
3. `find ./buildpacks  -name "package.toml" | xargs -n 1 ./scripts/mod-pkgtoml.sh`
4. Going to `paketo-buildpacks` directory and overriding `buildpack.toml`-s in sub-directories `bellsoft-liberica`, `syft`, and `watchexec` with files from `arm64-toml` directory.
5. `./scripts/build.sh paketo-buildpacks/java`

Here's the full output:
```
Paketo Buildpack for CA Certificates 3.6.1
  https://github.com/paketo-buildpacks/ca-certificates
  Creating package in ./out
  Pre-package with scripts/build.sh
    Adding LICENSE
    Adding NOTICE
    Adding README.md
    Adding bin/build
    Adding bin/detect
    Adding bin/helper
    Adding bin/main
    Adding buildpack.toml
Password:
Successfully created package paketo-buildpacks/ca-certificates-arm64:3.6.1
~/paketo-arm64/buildpacks/paketo-buildpacks/ca-certificates ~/paketo-arm64
~/paketo-arm64

Paketo Buildpack for BellSoft Liberica 10.1.0
  https://github.com/paketo-buildpacks/bellsoft-liberica
  Creating package in ./out
  Pre-package with scripts/build.sh
    Adding LICENSE
    Adding NOTICE
    Adding README.md
    Adding bin/build
    Adding bin/detect
    Adding bin/helper
    Adding bin/main
    Adding buildpack.toml
Successfully created package paketo-buildpacks/bellsoft-liberica-arm64:10.1.0
~/paketo-arm64/buildpacks/paketo-buildpacks/bellsoft-liberica ~/paketo-arm64
~/paketo-arm64

Paketo Buildpack for Yarn 1.1.5
  https://github.com/paketo-buildpacks/yarn
  Creating package in ./out
  Pre-package with ./scripts/build.sh
    Building run... Success!
    Linking detect... Success!
    Linking build... Success!
    Adding bin/build
    Adding bin/detect
    Adding bin/run
    Adding buildpack.toml
ERROR: creating buildpack from .: buildpack.version is required
```

I'm using MacBook pro M2.

Thanks

**Comment by dmikusa** [comment]
Hi, there's is a known issue with the Yarn/Node-Engine buildpacks which were recently added to the buildpacks.

Prior to running step #5, just remove those buildpacks from the buildpack order group in buildpack.toml and from the package.toml file. The build should work fine then.

Alternatively, you could edit the buildpack.toml for each of those buildpacks [this](https://github.com/paketo-buildpacks/yarn/blob/main/buildpack.toml#L3) and [this](https://github.com/paketo-buildpacks/node-engine/blob/main/buildpack.toml#L3) and add an entry for `version = "{{.version}}"` in the `[buildpack]` section. This is what's missing in the error above. I think that might fix things, but I haven't had a chance to run through and test everything just yet.

**Comment by Souljacker2** [comment]
Removing those buildpacks from buildpack.toml and package.toml files worked for me.
Thank you.
