### ISSUE TITLE
Springboot example 

### ISSUE THREAD

**Issue by gAmUssA** [dmikusa/paketo-arm64#3]
Is there example of how to build springboot image for arm64 platform using this buildpack?

**Comment by dmikusa** [comment]
If you follow the instructions in the [README.md](https://github.com/dmikusa-pivotal/paketo-arm64/blob/main/README.md) you will end up with a builder image. When you `pack build`, you give it the `-B <your-builder-image>` argument like `-B docker.io/dmikusa2pivotal/builder:focal`. This tells pack to use your builder (you can see more in the Samples section of the README).

With Spring Boot, if you're building through Maven or Gradle, you should follow all of the steps in the README up to the point where you're building the samples. Now, to use your builder with Spring Boot you need to edit your `pom.xml` or `build.gradle` file and instruct the Spring Boot plugin to use your builder.

- [For Gradle, see here](https://docs.spring.io/spring-boot/docs/2.6.3/gradle-plugin/reference/htmlsingle/#build-image.customization).
- [For Maven, see here](https://docs.spring.io/spring-boot/docs/2.6.3/maven-plugin/reference/htmlsingle/#build-image.customization).

In both cases, you just need to set the `builder` configuration item.

**Comment by gAmUssA** [comment]
@dmikusa-pivotal Thank you for this note. Is builder that I can reuse (instead of building myself)?

**Comment by dmikusa** [comment]
No, not yet. At least not anything official. The Paketo project isn't at a place where we can publish public ARM64 images at this time. There's still work to be done with the buildpack tools & also CI to make that happen in a way that we can support. There is every intention to publish public images, but we have work to do before that can happen.

This repo is a way for early adopters to build their own images. If someone were to want to build images using the scripts here and share those, that's totally fine by me. As a user, you just want to be aware that you trust any images published by a 3rd party and trust that those images will be kept up-to-date.

**Comment by dashaun** [comment]
@gAmUssA I pushed a builder to docker hub here: https://hub.docker.com/repository/docker/dashaun/native-builder

I used the scripts here (and I'm super excited) to build the images.

**Comment by dashaun** [comment]
@gAmUssA Here is an example that uses that builder ^^^

https://github.com/dashaun/spring-boot-native-pi

**Comment by gAmUssA** [comment]
@dashaun Thank you for putting this together. I have had some success in using QEMU with arm64 emulation to build an image (java based). I will try your example to build a native app using graalVM.
