### ISSUE TITLE
Getting "create-package: command not found"

### ISSUE THREAD

**Issue by Souljacker2** [dmikusa/paketo-arm64#9]
Hi,
When running [build.sh script](https://github.com/dmikusa/paketo-arm64/blob/main/scripts/build.sh) (last step on [Package your Buildpacks](https://github.com/dmikusa/paketo-arm64#package-your-buildpacks)) I'm getting:
`./scripts/build.sh: line 28: create-package: command not found`.
Is there any tool I should install to make it work?
I'm using MacBook pro M2.

Thanks

**Comment by dmikusa** [comment]
See #4 here -> https://github.com/dmikusa/paketo-arm64#prerequisites

**Comment by Souljacker2** [comment]
> See #4 here -> https://github.com/dmikusa/paketo-arm64#prerequisites

I already followed this step. Trying to execute it again:
```
souljacker@Souljacker-MacBook-Pro paketo-arm64 % go install github.com/paketo-buildpacks/libpak/cmd/create-package@v1.64.0
go: downloading github.com/paketo-buildpacks/libpak v1.64.0
go: downloading github.com/buildpacks/libcnb v1.27.0
go: downloading github.com/Masterminds/semver/v3 v3.2.0
go: downloading github.com/imdario/mergo v0.3.14
go: downloading github.com/onsi/gomega v1.27.4
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading github.com/mattn/go-isatty v0.0.17
go: downloading github.com/BurntSushi/toml v1.2.1
go: downloading golang.org/x/sys v0.6.0
souljacker@Souljacker-MacBook-Pro paketo-arm64 % ./scripts/build.sh paketo-buildpacks/java           
./scripts/build.sh: line 28: create-package: command not found
```

Edit: I ran `export PATH=$PATH:$HOME/go/bin` once more and now it's working.

Thank you.

**Comment by dmikusa** [comment]
Oh, great. I was just about to suggest checking `$PATH`.
